# Generated by Django 5.0.2 on 2024-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
