# Generated by Django 5.0.2 on 2024-03-19 16:24

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_date_created_owner_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[car.models.validate_year]),
        ),
    ]
